[package]
name = "rs-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
mongodb = "2.8.2"
rocket = { version = "0.5.0", features = ["json", "serde_json"] }
serde = "1.0.198"
